pre-commit:
  parallel: true
  commands:
    oxlint:
      run: bun run lint
    oxfmt:
      run: bun run format:check
    tsc:
      run: bun run typecheck

commit-msg:
  commands:
    commitlint:
      run: bunx commitlint --edit ${1}
